services:
  nginx:
    image: nginx:alpine
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt/:ro
    networks:
      - app-network

  frontend-blue:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    depends_on:
      - nginx
    networks:
      - app-network

  frontend-green:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    external: true
