services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letescrypt:/etc/letsencrypt/:ro

  frontend-blue:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    depends_on:
      - nginx

  frontend-green:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    depends_on:
      - nginx

networks:
  app-network:
    external: true
